clc;
clear functions;

if isfile("OpticalFlow2d.mex");
  delete("OpticalFlow2d.mex");
end

disp("Compiling...");

mkoctfile --mex ...
  -o "OpticalFlow2d.mex" ...
  -lfftw3 ...
  WrapperOpticalFlow2d.cpp ...
  src/Image.cpp ...
  src/Motion.cpp ...
  src/Logger.cpp ...
  src/Kernel.cpp ...
  src/regularization/IterativeSolver.cpp ...
  src/regularization/OpticalFlow/OpticalFlow.cpp ...
  src/regularization/OpticalFlow/OpticalFlowDiffusion.cpp ...
  src/ImageRegistration.cpp

disp("Compilation success!");
